PROD321-5973: free credit score
321ignition/dealer-brightonmotorsonline pull request #17
Opened 2020-09-02 16:33 UTC by estradag87

[feature/PROD321-5973/free-credit-score](https://321ignitionproj.atlassian.net/browse/PROD321-5973)

This PR includes:
- Title and Metadata
- Logos 
- Copy

![Captura de Pantalla 2020-09-02 a la(s) 11 28 29 a  m](https://user-images.githubusercontent.com/64660841/92011002-14a77580-ed10-11ea-9160-b54a8470ef8e.png)
![Captura de Pantalla 2020-09-02 a la(s) 11 28 38 a  m](https://user-images.githubusercontent.com/64660841/92011006-16713900-ed10-11ea-95e0-871759ee9fe6.png)
![Captura de Pantalla 2020-09-02 a la(s) 11 29 56 a  m](https://user-images.githubusercontent.com/64660841/92011013-183afc80-ed10-11ea-93e8-fa780af1f496.png)

2020-09-02 21:19 UTC, GabrielaDiazB requested changes

2020-09-02 21:19 UTC, GabrielaDiazB commented on _site/templates/pages/free-credit-score.md
> +description: 'Find Out Exactly How Much Car You Can Afford With Your Free FICO<sup>®</sup> Auto Score. Fast Auto Loan Approvals For All Types of Credit: Good, Bad, or No Credit.'
In the description, the <sup>  tag is not going to be read as HTML, I don't think is necessary.

2020-09-03 18:29 UTC, estradag87 commented on _site/templates/pages/free-credit-score.md
> +description: 'Find Out Exactly How Much Car You Can Afford With Your Free FICO<sup>®</sup> Auto Score. Fast Auto Loan Approvals For All Types of Credit: Good, Bad, or No Credit.'
fixed

2020-09-03 21:15 UTC, GabrielaDiazB approved these changes

2020-09-03 21:15 UTC, merged