PROD321-5985 - Homepage Promos
321ignition/dealer-brightonmotorsonline pull request #19
Opened 2020-09-02 18:56 UTC by frankynztein

## Overview

Updated copy ans styles for Homepage promos. I asked for the icon in Promo 1. This will be updated as soon as a I get that file.

Connects [PROD321-5985](https://321ignitionproj.atlassian.net/browse/PROD321-5985)

 ### Demo

![image](https://user-images.githubusercontent.com/47264573/92024402-c7cd9a00-ed23-11ea-95ba-24a245dbc021.png)

2020-09-02 19:45 UTC, GabrielaDiazB requested changes

2020-09-02 19:45 UTC, GabrielaDiazB commented on _site/scss/home.scss
> +    background-color: $secondary;
We have a variable for the first banner `$first-ad-banner-background`

2020-09-02 19:45 UTC, GabrielaDiazB commented on _site/scss/home.scss
> +    }
Please use helpers before overwriting the styles. The ads are freestyle you can use the `font-size-14` for this.

2020-09-02 19:45 UTC, GabrielaDiazB commented on _site/scss/home.scss
> +    }
Same here, use helpers before overwriting

2020-09-02 19:45 UTC, GabrielaDiazB commented on _site/templates/banners/ads.md
> +          <img class="w-50 pl-3 mb-3" src="" alt="">
If you are not going to use an image here, then please remove the tag

2020-09-02 21:07 UTC, frankynztein commented on _site/scss/home.scss
> +    background-color: $secondary;
Done.

2020-09-02 21:07 UTC, frankynztein commented on _site/scss/home.scss
> +    }
Done.

2020-09-02 21:07 UTC, frankynztein commented on _site/scss/home.scss
> +    }
Done.

2020-09-02 21:08 UTC, frankynztein commented on _site/templates/banners/ads.md
> +          <img class="w-50 pl-3 mb-3" src="" alt="">
I'm actually waiting for the image/icon (not sure) that goes there.

2020-09-09 17:41 UTC, GabrielaDiazB approved these changes

2020-09-09 17:41 UTC, merged