PROD321-6756: Test-drive-button
321ignition/dealer-brightonmotorsonline pull request #94
Opened 2020-09-16 21:09 UTC by estradag87

[feature/PROD321-6756/test-drive-button](https://321ignitionproj.atlassian.net/browse/PROD321-6756)

Fix the carousel-wrapper and the yellow-button style
 
![Captura de Pantalla 2020-09-16 a la(s) 4 06 24 p  m](https://user-images.githubusercontent.com/64660841/93392681-d42f1800-f836-11ea-9183-bb884daff2bd.png)
![Captura de Pantalla 2020-09-16 a la(s) 4 06 00 p  m](https://user-images.githubusercontent.com/64660841/93392690-d7c29f00-f836-11ea-931d-fdfe0c2fb376.png)

2020-09-16 23:00 UTC, GabrielaDiazB approved these changes

2020-09-16 23:01 UTC, GabrielaDiazB requested changes

2020-09-16 23:01 UTC, GabrielaDiazB commented on _site/templates/ssr-data/css/common.pug
> +
If this modal only shows in the VDP then you should move this css to the cars.pug. If this appears in other SSR pages, then please ignore this comment.

2020-09-17 15:22 UTC, estradag87 commented on _site/templates/ssr-data/css/common.pug
> +
Done!

2020-09-17 16:38 UTC, GabrielaDiazB approved these changes

2020-09-17 16:38 UTC, merged